CREATE DATABASE kasdb CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE kasdb;

CREATE TABLE anak (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nama VARCHAR(100) NOT NULL,
  tanggal_daftar DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE kas (
  id INT AUTO_INCREMENT PRIMARY KEY,
  anak_id INT NOT NULL,
  jumlah INT NOT NULL,
  tanggal DATETIME DEFAULT CURRENT_TIMESTAMP,
  keterangan VARCHAR(255) DEFAULT NULL,
  FOREIGN KEY (anak_id) REFERENCES anak(id) ON DELETE CASCADE
);
